/*
 *  hashtest.c
 *  
 *
 *  Created by Wade Norris on 2/17/10.
 *  Copyright 2010 University of California: Los Angeles. All rights reserved.
 *
 */


#include <stdio.h>
#include <stdlib.h>

/*
 *  rollready_hash(const char* bytes, int length, unsigned_int* hash_value)
 *  
 *
 *  Used to hash string values using base an odd prime number as a number base.
 *  Order of Magnitude: O(length)
 *
 */
void rollready_hash(const char* data, int length, unsigned int* hash_value)
{	
	int multiplier = 1;	
	*hash_value = 0;
	int i;
	for(i=length-1; i>=0; i--)
	{
		*hash_value += (multiplier * data[i]);
		multiplier *= 101;
	}	
}

unsigned int curhash = 0;
int cur = 0;
int mylength = 130;

int roll(char* data, int length)
{
	int returnval;
	rollready_hash(data+cur, 1, &returnval);
	int temp = returnval;
	int i;
	for(i=1; i<length; i++)
		temp *= 101;
	curhash -= temp;
	curhash *= 101;
	rollready_hash(data+cur+length, 1, &returnval);
	curhash += returnval;
	cur++;
}

int main(void)
{
	char* word = "hellotheregoodsirthisstring is supposed to be verylongtofindoutwhenthereisoverflowbutitusuallyhappensatchar8sothisismorethanenough";
	printf("Hash Test\n\n");
	
	/****************************************
	 THIS CODE IS USED TO CHECK WHEN THERE WILL BE OVERFLOW 
	
	unsigned int lasthash = 0;
	rollready_hash(word, 1, &curhash);
	int i;
	for(i=2;lasthash<curhash;i++)
	{
		lasthash = curhash;
		rollready_hash(word, i, &curhash);
		printf("hash() = %u\n\n", curhash);
	}
	
	printf("LENGTH WITH OVERFLOW = %d\n\n", i);
	
	/* END OVERFLOW CHECK. FOUND OVERFLOW VALUE OF LENGTH 8
	   ANY USE OF HASH WITH STRINGS LONGER THAN 7 or 8 IS DANGEROUS
	   AND UNPREDICTABLE. USE CAUTION!
	 ****************************************/
	
	/****************************************
	 THE FOLLOWING CODE TESTS THE ROLING HASH FUNCTION BY MANUALY
	 HASHING STRING SEGMENTS OF LENGTH 4 STARTING AT INDEX 0 OF 
	 THE LONG STRING AND REHASHING AT INDEXES 1, 2, AND 3.   
	 
	 NEXT IN THE SECOND SEGMENT THE FIRST SET OF 4 CHARACTERS IS 
	 HASHED AND USING THE ROLLING HASH FEATURE AND THE ROLL FUNCTION
	 THE NEW HASHES FOR INDEXES 1, 2, AND 3 ARE COMPUTED WITHOUT
	 FULLY RE-HASHING.*/
	
	// Manual full hash of each 
	
	int i;
	for(i=0; i+mylength+5 < mylength; i++)
	{
		rollready_hash(word+i, 4, &curhash);
		printf("hash(h) = %u\n\n", curhash);
	}
	
	// Rolling hash where first is fully hashed
	// then new ones are generated by subtracting
	// the hash value of the first character
	// and adding the hash value of the next character
	// in the string.
	
	rollready_hash(word, 4, &curhash);
	printf("First hash value = %u\n", curhash);
	
	while((cur+mylength+5) < mylength)
	{
		roll(word, 4);
		printf("Next hash value = %u\n", curhash);
	}
	
	/* END OF ROLLING HASH TEST
	 ****************************************/
}